server:
  port: 8083
  servlet:
    context-path: /file
spring:
  application:
    name: spring-cloud-file
eureka:
  client:
    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
